### ISSUE TITLE
list length check needed

### ISSUE THREAD

**Issue by ameynert** [MultiQC/MultiQC_bcbio#15]
https://github.com/MultiQC/MultiQC_bcbio/blob/6d532abd95adaf3c07761528718b3cbf42efc3b9/multiqc_bcbio/srna.py#L36

I'm getting errors running this module within bcbio. A simple if (len(cols) > 0): on the previous line fixes it.

**Comment by lpantano** [comment]
Thanks, I just submitted the commit. When travis comes back clean I'll update bioconda recipe.
